### ISSUE TITLE
VST Plug-in Version?

### ISSUE THREAD

**Issue by AlexW00** [austintheriot/audio#1]
Hi there, I love the granular synth demo you built. Do you intend to create a VST version of it? If not, what's the license under which the code is licensed? I would be interested in creating a fork to continue the development of the plugin as a VST3 / Clap plugin (MIT Licensed, open source).

**Comment by austintheriot** [comment]
Hi Alexander! I have no intent to create a VST version of it. The license for the code itself is MIT/Apache-2.0 (take your pick)--(see the [audio Cargo.toml](https://github.com/austintheriot/audio/blob/afae1bf80647b9b4eed20a85ecaa2eaa0b556e37/audio/Cargo.toml) and the[ demo Cargo.toml](https://github.com/austintheriot/audio/blob/afae1bf80647b9b4eed20a85ecaa2eaa0b556e37/demos/granular_synthesizer/Cargo.toml)). 

However, any audio files in the repo are copyrighted, since they are my own compositions (i.e. any file in the `audio/assets` directory, such as [this one](https://github.com/austintheriot/audio/blob/afae1bf80647b9b4eed20a85ecaa2eaa0b556e37/assets/ecce_nova_1.mp3)).

Feel free to use the code however you wish--though credit is always much appreciated.

Would love to see the results of whatever you make!

**Comment by AlexW00** [comment]
Thank you for the reply, that's great to hear! I will of course credit & tell you if I create anything based on your code.
